title: 謝明炫 Mingxuan Xie 
author: ©2018-2021 Mingxuan Xie
email: designer.mingxuan@gmail.com
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "show_excerpts:"
  謝明炫 Mingxuan Xie: Vrchitect / Indie Dev / XR Innovator / Founder of Vrch and Member of Hyperbation.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b %Y"

  # generate social links in footer
  social_links:
    twitter: MingxuanXie
    github: MingxuanXie
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: mingxuan.fun
    linkedin: mingxuan-xie
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCs7_mSIr5eiaSDsPt47DzMQ
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    #
    # Mastodon instances
    mastodon:
    - username: mingxuan
      instance: social.caa-ins.org
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Comment out Build settings to avoid conflict with github pages

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Use GitHub Flavored Markdown
# markdown: CommonMarkGhPages
markdown: kramdown

# Exclude certain directory and files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - MarkdownCheatsheet.md
  - minimaREADME.md
    # - /app